spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/takehome-sicred
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
app:
  dominio: http://ec2-54-80-39-210.compute-1.amazonaws.com