spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/takehome_sicred
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
app:
  dominio: http://dominio